### PR TITLE
Allow full request error description in case of HTTP RC 400

### PR DESCRIPTION
**Pull request by develart-projects**
As we haven't any possibility to get details about wrong input params in current code, please consider to allow RC 400 to throw Exception with details. Seems to be the case before, but now is parsing restricted to RC below 300.

Thank you.

### CODE REVIEW

**Comment by malcanek** [comment]
This makes sence to me but it should probably load error message somewhere else than to data variable. I'll take a closer look and try to modificate it.

**Comment by develart-projects** [comment]
That line is actually not in use, so I simply removed it. Exception is thrown right away

**Comment by develart-projects** [comment]
Can you please kindly review and either merge or decline? I have to push into production and need to decide, if to use your client or my fork.

Thank you in advance.

**Comment by malcanek** [comment]
I finally found another solution. I don't know why I put 400 check into parseJSON but it makes no sence to me now. So I removed it and updated construct of iDokladResponse so it holds also raw output (I don't know why but iDoklad api responses both text string (e.g. 404) and json so I cannot parse it before I know that code is lower than 300).

Now if you don't have httpExceptions on, you can get raw output from iDokladResponse with getRaw method. If you use httpExceptions, you can get raw output from exception thrown with method getPayload called on catched exception.

I hope this solves your problem.

**Pull request closed without merging**
